name: "Github Actions Berlin Weather Bot"

on: 
    schedule:
        - cron: '37 14 * * *'

jobs:
    bot:
        runs-on: ubuntu-latest
        steps:
            - name: 'Install node'
              uses: actions/setup-node@v1
            - name: 'Install NPM dependencies'
              run: npm install
            - name: 'Build application'
              run: npm build
            - name: 'Run application'
              run: npm start
              env:
                OPEN_WEATHER_API_TOKEN: ${{ secrets.OPEN_WEATHER_API_TOKEN }}
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}        
                LOCATION: ${{ secrets.LOCATION }}
